Repository GSM-MSG/GUI-iOS, pull requests merged in 2023-01, with the labels that each got.

#6 🔀 :: Makefile Refactor
  Makefile
Labels: 3️⃣ Priority: Low, ♻️ Refactor, ⚡️ Simple

#7 🔀 :: 통신 라이브러리 추가
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/Services/BaseService/Project.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Project+Template.swift
Labels: 1️⃣ Priority: High, ⚙ Setting

#11 :zap: Dependency-Injection-library
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/Shared/GlobalThirdPartyLibrary/Project.swift
  Tuist/Dependencies.swift
Labels: 3️⃣ Priority: Low

#13 🔀:: Miniature-Dependency
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/Shared/GlobalThirdPartyLibrary/Project.swift
  Tuist/Dependencies.swift
Labels: 3️⃣ Priority: Low

#10 :zap: dependency libraries
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/Features/BaseFeature/Project.swift
  Tuist/Dependencies.swift
Labels: 3️⃣ Priority: Low

#19 🔀 :: Color 시스템 / System Color 영역 작업
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/Core/DesignSystem/Project.swift
  Projects/Core/DesignSystem/Resources/Colors.xcassets/Contents.json
  Projects/Core/DesignSystem/Resources/Colors.xcassets/System/Black.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/Colors.xcassets/System/Contents.json
  Projects/Core/DesignSystem/Resources/Colors.xcassets/System/Negative.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/Colors.xcassets/System/Positive.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/Colors.xcassets/System/White.colorset/Contents.json
  Projects/Core/DesignSystem/Sources/Color/Color+gui.swift
  Projects/Core/DesignSystem/Sources/Color/GUIColorSystem+System.swift
  Projects/Core/DesignSystem/Sources/Color/GUIColorable.swift
  Projects/Core/DesignSystem/Sources/Feature.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#21 🔀 :: Moordinator 버전 업그레이드
  Tuist/Dependencies.swift
Labels: 0️⃣ Priority: Critical

#24 🔀 :: CODEOWNERS 설정
  .github/CODEOWNERS
Labels: 2️⃣ Priority: Medium, ⚙ Setting

#29 🔀 :: BaseViewController
  Projects/Features/BaseFeature/Sources/BaseViewController.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#33 🔀 :: 테스트 프레임워크 설정
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Project+Template.swift
Labels: 1️⃣ Priority: High, ⚙ Setting

#38 🔀 :: CI 구성
  .github/workflows/CachingTuistDependencies.yml
  .github/workflows/PR_CI.yml
  Projects/App/Project.swift
  Tuist/ProjectDescriptionHelpers/Project+Template.swift
Labels: 1️⃣ Priority: High, ⚙ Setting, 🌏 Deploy

#36 🔀 :: Combine의 extension들 추가
  Projects/Features/BaseFeature/Sources/Base/BaseViewController.swift
  Projects/Features/BaseFeature/Sources/Base/BaseViewModel.swift
  Projects/Features/BaseFeature/Sources/BaseViewController.swift
  Projects/Features/BaseFeature/Sources/BoundsProvidable.swift
  Projects/Features/BaseFeature/Sources/LifeCyclePublishable.swift
  Projects/Shared/CombineExtension/Sources/AnyPublisher/AnyPublisher+create.swift
  Projects/Shared/CombineExtension/Sources/AnyPublisher/AnyPublisher+typeErase.swift
  Projects/Shared/CombineExtension/Sources/Internal/DemandBuffer.swift
  Projects/Shared/CombineExtension/Sources/Publisher/Publisher+sink.swift
  Projects/Shared/CombineExtension/Sources/Source.swift
Labels: 1️⃣ Priority: High, ♻️ Refactor, ⚙ Setting

#39 🔀 :: RouteProvidable Protocol 분리
  Projects/Features/BaseFeature/Sources/Base/BaseViewModel.swift
  Projects/Features/BaseFeature/Sources/RouterProvidable.swift
Labels: 2️⃣ Priority: Medium, ♻️ Refactor, ⚡️ Simple

#43 :bento: primary color asset add
  Projects/Core/DesignSystem/Resources/Colors.xcassets/Primary/Contents.json
  Projects/Core/DesignSystem/Resources/Colors.xcassets/Primary/M20.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/Colors.xcassets/Primary/M40.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/Colors.xcassets/Primary/M60.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/Colors.xcassets/Primary/S20.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/Colors.xcassets/Primary/S40.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/Colors.xcassets/Primary/S60.colorset/Contents.json
  Projects/Core/DesignSystem/Sources/Color/Color+gui.swift
  Projects/Core/DesignSystem/Sources/Color/GUIColorSystem+Primary.swift
Labels: 3️⃣ Priority: Low

#41 🔀 :: gray color 적용
  Projects/Core/DesignSystem/Resources/Colors.xcassets/Gray/Contents.json
  Projects/Core/DesignSystem/Resources/Colors.xcassets/Gray/G120.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/Colors.xcassets/Gray/G20.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/Colors.xcassets/Gray/G40.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/Colors.xcassets/Gray/G80.colorset/Contents.json
  Projects/Core/DesignSystem/Sources/Color/Color+gui.swift
  Projects/Core/DesignSystem/Sources/Color/GUIColorSystem+Gray.swift
Labels: 1️⃣ Priority: High

#48 🔀 :: 디펜던시 추가 스크립팅
  Makefile
  Scripts/NewDependency.swift
Labels: 1️⃣ Priority: High, ⚙ Setting, ⚡️performance
